apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        # forward . 172.16.0.1
        cache 30
        loop
        reload
        loadbalance
    }
    internal.home:53 {
        errors
        cache 30
        forward . 192.168.1.50
    }

kind: ConfigMap
metadata:
#   annotations:
#     kubectl.kubernetes.io/last-applied-configuration: |
#       {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health {\n       lameduck 5s\n    }\n    ready\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n       pods insecure\n       fallthrough in-addr.arpa ip6.arpa\n       ttl 30\n    }\n    prometheus :9153\n    forward . /etc/resolv.conf {\n       max_concurrent 1000\n    }\n    # forward . 172.16.0.1\n    cache 30\n    loop\n    reload\n    loadbalance\n    internal.home:53 {\n      errors\n      cache 30\n      forward . 192.168.1.50\n    }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-04-12T07:35:09Z","name":"coredns","namespace":"kube-system","resourceVersion":"87887","uid":"1dbfebb4-e51e-4b54-8291-6f9e913d503f"}}
#   creationTimestamp: "2024-04-12T07:35:09Z"
  name: coredns
  namespace: kube-system
#   resourceVersion: "88735"
#   uid: 1dbfebb4-e51e-4b54-8291-6f9e913d503f
